// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: protobuf/tunnel.proto

package tunnel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgniTunnel_Connect_FullMethodName = "/tunnel.AgniTunnel/Connect"
)

// AgniTunnelClient is the client API for AgniTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgniTunnelClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type agniTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgniTunnelClient(cc grpc.ClientConnInterface) AgniTunnelClient {
	return &agniTunnelClient{cc}
}

func (c *agniTunnelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgniTunnel_ServiceDesc.Streams[0], AgniTunnel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgniTunnel_ConnectClient = grpc.BidiStreamingClient[Envelope, Envelope]

// AgniTunnelServer is the server API for AgniTunnel service.
// All implementations must embed UnimplementedAgniTunnelServer
// for forward compatibility.
type AgniTunnelServer interface {
	Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedAgniTunnelServer()
}

// UnimplementedAgniTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgniTunnelServer struct{}

func (UnimplementedAgniTunnelServer) Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgniTunnelServer) mustEmbedUnimplementedAgniTunnelServer() {}
func (UnimplementedAgniTunnelServer) testEmbeddedByValue()                    {}

// UnsafeAgniTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgniTunnelServer will
// result in compilation errors.
type UnsafeAgniTunnelServer interface {
	mustEmbedUnimplementedAgniTunnelServer()
}

func RegisterAgniTunnelServer(s grpc.ServiceRegistrar, srv AgniTunnelServer) {
	// If the following call panics, it indicates UnimplementedAgniTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgniTunnel_ServiceDesc, srv)
}

func _AgniTunnel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgniTunnelServer).Connect(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgniTunnel_ConnectServer = grpc.BidiStreamingServer[Envelope, Envelope]

// AgniTunnel_ServiceDesc is the grpc.ServiceDesc for AgniTunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgniTunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.AgniTunnel",
	HandlerType: (*AgniTunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgniTunnel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/tunnel.proto",
}
