// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: maps/maps.proto

package maps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED      ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_FOUND        ErrorCode = 2
	ErrorCode_ERROR_CODE_ALREADY_EXISTS   ErrorCode = 3
	ErrorCode_ERROR_CODE_UNAVAILABLE      ErrorCode = 4
	ErrorCode_ERROR_CODE_INTERNAL         ErrorCode = 5
	ErrorCode_ERROR_CODE_UNAUTHORIZED     ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_ALREADY_EXISTS",
		4: "ERROR_CODE_UNAVAILABLE",
		5: "ERROR_CODE_INTERNAL",
		6: "ERROR_CODE_UNAUTHORIZED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":      0,
		"ERROR_CODE_INVALID_ARGUMENT": 1,
		"ERROR_CODE_NOT_FOUND":        2,
		"ERROR_CODE_ALREADY_EXISTS":   3,
		"ERROR_CODE_UNAVAILABLE":      4,
		"ERROR_CODE_INTERNAL":         5,
		"ERROR_CODE_UNAUTHORIZED":     6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_maps_maps_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_maps_maps_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=maps.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_maps_maps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GatewayPutRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Region             string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	GatewayIp          string                 `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayPort        int32                  `protobuf:"varint,3,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	WssPort            int32                  `protobuf:"varint,4,opt,name=wss_port,json=wssPort,proto3" json:"wss_port,omitempty"`
	Capacity           *Capacity              `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,6,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GatewayPutRequest) Reset() {
	*x = GatewayPutRequest{}
	mi := &file_maps_maps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPutRequest) ProtoMessage() {}

func (x *GatewayPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPutRequest.ProtoReflect.Descriptor instead.
func (*GatewayPutRequest) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayPutRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayPutRequest) GetGatewayPort() int32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *GatewayPutRequest) GetWssPort() int32 {
	if x != nil {
		return x.WssPort
	}
	return 0
}

func (x *GatewayPutRequest) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *GatewayPutRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       int32                  `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Bandwidth     int32                  `protobuf:"varint,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_maps_maps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{2}
}

func (x *Capacity) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Capacity) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Capacity) GetStorage() int32 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *Capacity) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

type GatewayResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewayIp      string                 `protobuf:"bytes,2,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayAddress string                 `protobuf:"bytes,3,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	GatewayPort    int32                  `protobuf:"varint,4,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	WssPort        int32                  `protobuf:"varint,5,opt,name=wss_port,json=wssPort,proto3" json:"wss_port,omitempty"`
	Capacity       *Capacity              `protobuf:"bytes,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Error          *Error                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Identity       string                 `protobuf:"bytes,8,opt,name=Identity,proto3" json:"Identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	mi := &file_maps_maps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayResponse) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *GatewayResponse) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *GatewayResponse) GetGatewayPort() int32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *GatewayResponse) GetWssPort() int32 {
	if x != nil {
		return x.WssPort
	}
	return 0
}

func (x *GatewayResponse) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *GatewayResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GatewayResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type AgentConnectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentDomain        string                 `protobuf:"bytes,1,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,2,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	GatewayId          string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Region             string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentConnectionRequest) Reset() {
	*x = AgentConnectionRequest{}
	mi := &file_maps_maps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConnectionRequest) ProtoMessage() {}

func (x *AgentConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConnectionRequest.ProtoReflect.Descriptor instead.
func (*AgentConnectionRequest) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{4}
}

func (x *AgentConnectionRequest) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentConnectionRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

func (x *AgentConnectionRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentConnectionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type AgentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentDomain    string                 `protobuf:"bytes,2,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	GatewayId      string                 `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewayAddress string                 `protobuf:"bytes,4,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	GatewayPort    int32                  `protobuf:"varint,5,opt,name=gateway_port,json=gatewayPort,proto3" json:"gateway_port,omitempty"`
	WssPort        int32                  `protobuf:"varint,6,opt,name=wss_port,json=wssPort,proto3" json:"wss_port,omitempty"`
	Capacity       *Capacity              `protobuf:"bytes,7,opt,name=capacity,proto3" json:"capacity,omitempty"`
	GatewayIp      string                 `protobuf:"bytes,8,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	Error          *Error                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Identity       string                 `protobuf:"bytes,10,opt,name=Identity,proto3" json:"Identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_maps_maps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{5}
}

func (x *AgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentResponse) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *AgentResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *AgentResponse) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *AgentResponse) GetGatewayPort() int32 {
	if x != nil {
		return x.GatewayPort
	}
	return 0
}

func (x *AgentResponse) GetWssPort() int32 {
	if x != nil {
		return x.WssPort
	}
	return 0
}

func (x *AgentResponse) GetCapacity() *Capacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *AgentResponse) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *AgentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AgentResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type GatewayHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayHandshake) Reset() {
	*x = GatewayHandshake{}
	mi := &file_maps_maps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHandshake) ProtoMessage() {}

func (x *GatewayHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHandshake.ProtoReflect.Descriptor instead.
func (*GatewayHandshake) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayHandshake) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type MultipleGateways struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*GatewayResponse     `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleGateways) Reset() {
	*x = MultipleGateways{}
	mi := &file_maps_maps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleGateways) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleGateways) ProtoMessage() {}

func (x *MultipleGateways) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleGateways.ProtoReflect.Descriptor instead.
func (*MultipleGateways) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{7}
}

func (x *MultipleGateways) GetGateways() []*GatewayResponse {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *MultipleGateways) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ProxyMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentDomain   string                 `protobuf:"bytes,1,opt,name=agent_domain,json=agentDomain,proto3" json:"agent_domain,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ProxyId       string                 `protobuf:"bytes,3,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMapping) Reset() {
	*x = ProxyMapping{}
	mi := &file_maps_maps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMapping) ProtoMessage() {}

func (x *ProxyMapping) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMapping.ProtoReflect.Descriptor instead.
func (*ProxyMapping) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{8}
}

func (x *ProxyMapping) GetAgentDomain() string {
	if x != nil {
		return x.AgentDomain
	}
	return ""
}

func (x *ProxyMapping) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProxyMapping) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

type ProxyConnectionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Region             string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,3,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProxyConnectionRequest) Reset() {
	*x = ProxyConnectionRequest{}
	mi := &file_maps_maps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConnectionRequest) ProtoMessage() {}

func (x *ProxyConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConnectionRequest.ProtoReflect.Descriptor instead.
func (*ProxyConnectionRequest) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{9}
}

func (x *ProxyConnectionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProxyConnectionRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

type SeederRegistrationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dns                string                 `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	SeedIp             string                 `protobuf:"bytes,3,opt,name=seed_ip,json=seedIp,proto3" json:"seed_ip,omitempty"`
	SeedPort           string                 `protobuf:"bytes,4,opt,name=seed_port,json=seedPort,proto3" json:"seed_port,omitempty"`
	Region             string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	VerifiableCredHash string                 `protobuf:"bytes,6,opt,name=verifiable_cred_hash,json=verifiableCredHash,proto3" json:"verifiable_cred_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SeederRegistrationRequest) Reset() {
	*x = SeederRegistrationRequest{}
	mi := &file_maps_maps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeederRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeederRegistrationRequest) ProtoMessage() {}

func (x *SeederRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeederRegistrationRequest.ProtoReflect.Descriptor instead.
func (*SeederRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{10}
}

func (x *SeederRegistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeederRegistrationRequest) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *SeederRegistrationRequest) GetSeedIp() string {
	if x != nil {
		return x.SeedIp
	}
	return ""
}

func (x *SeederRegistrationRequest) GetSeedPort() string {
	if x != nil {
		return x.SeedPort
	}
	return ""
}

func (x *SeederRegistrationRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SeederRegistrationRequest) GetVerifiableCredHash() string {
	if x != nil {
		return x.VerifiableCredHash
	}
	return ""
}

type SeederResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeederId      string                 `protobuf:"bytes,1,opt,name=seeder_id,json=seederId,proto3" json:"seeder_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dns           string                 `protobuf:"bytes,3,opt,name=dns,proto3" json:"dns,omitempty"`
	SeedIp        string                 `protobuf:"bytes,4,opt,name=seed_ip,json=seedIp,proto3" json:"seed_ip,omitempty"`
	SeedPort      string                 `protobuf:"bytes,5,opt,name=seed_port,json=seedPort,proto3" json:"seed_port,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Identity      string                 `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
	Error         *Error                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeederResponse) Reset() {
	*x = SeederResponse{}
	mi := &file_maps_maps_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeederResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeederResponse) ProtoMessage() {}

func (x *SeederResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeederResponse.ProtoReflect.Descriptor instead.
func (*SeederResponse) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{11}
}

func (x *SeederResponse) GetSeederId() string {
	if x != nil {
		return x.SeederId
	}
	return ""
}

func (x *SeederResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeederResponse) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *SeederResponse) GetSeedIp() string {
	if x != nil {
		return x.SeedIp
	}
	return ""
}

func (x *SeederResponse) GetSeedPort() string {
	if x != nil {
		return x.SeedPort
	}
	return ""
}

func (x *SeederResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SeederResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *SeederResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SeederQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeederQueryRequest) Reset() {
	*x = SeederQueryRequest{}
	mi := &file_maps_maps_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeederQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeederQueryRequest) ProtoMessage() {}

func (x *SeederQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeederQueryRequest.ProtoReflect.Descriptor instead.
func (*SeederQueryRequest) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{12}
}

func (x *SeederQueryRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type MultipleSeeders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seeders       []*SeederResponse      `protobuf:"bytes,1,rep,name=seeders,proto3" json:"seeders,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleSeeders) Reset() {
	*x = MultipleSeeders{}
	mi := &file_maps_maps_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleSeeders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleSeeders) ProtoMessage() {}

func (x *MultipleSeeders) ProtoReflect() protoreflect.Message {
	mi := &file_maps_maps_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleSeeders.ProtoReflect.Descriptor instead.
func (*MultipleSeeders) Descriptor() ([]byte, []int) {
	return file_maps_maps_proto_rawDescGZIP(), []int{13}
}

func (x *MultipleSeeders) GetSeeders() []*SeederResponse {
	if x != nil {
		return x.Seeders
	}
	return nil
}

func (x *MultipleSeeders) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_maps_maps_proto protoreflect.FileDescriptor

const file_maps_maps_proto_rawDesc = "" +
	"\n" +
	"\x0fmaps/maps.proto\x12\x04maps\"F\n" +
	"\x05Error\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.maps.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe6\x01\n" +
	"\x11GatewayPutRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12!\n" +
	"\fgateway_port\x18\x03 \x01(\x05R\vgatewayPort\x12\x19\n" +
	"\bwss_port\x18\x04 \x01(\x05R\awssPort\x12*\n" +
	"\bcapacity\x18\x05 \x01(\v2\x0e.maps.CapacityR\bcapacity\x120\n" +
	"\x14verifiable_cred_hash\x18\x06 \x01(\tR\x12verifiableCredHash\"l\n" +
	"\bCapacity\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x05R\x06memory\x12\x18\n" +
	"\astorage\x18\x03 \x01(\x05R\astorage\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\x05R\tbandwidth\"\xa1\x02\n" +
	"\x0fGatewayResponse\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x02 \x01(\tR\tgatewayIp\x12'\n" +
	"\x0fgateway_address\x18\x03 \x01(\tR\x0egatewayAddress\x12!\n" +
	"\fgateway_port\x18\x04 \x01(\x05R\vgatewayPort\x12\x19\n" +
	"\bwss_port\x18\x05 \x01(\x05R\awssPort\x12*\n" +
	"\bcapacity\x18\x06 \x01(\v2\x0e.maps.CapacityR\bcapacity\x12!\n" +
	"\x05error\x18\a \x01(\v2\v.maps.ErrorR\x05error\x12\x1a\n" +
	"\bIdentity\x18\b \x01(\tR\bIdentity\"\xa4\x01\n" +
	"\x16AgentConnectionRequest\x12!\n" +
	"\fagent_domain\x18\x01 \x01(\tR\vagentDomain\x120\n" +
	"\x14verifiable_cred_hash\x18\x02 \x01(\tR\x12verifiableCredHash\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"\xdd\x02\n" +
	"\rAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fagent_domain\x18\x02 \x01(\tR\vagentDomain\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayId\x12'\n" +
	"\x0fgateway_address\x18\x04 \x01(\tR\x0egatewayAddress\x12!\n" +
	"\fgateway_port\x18\x05 \x01(\x05R\vgatewayPort\x12\x19\n" +
	"\bwss_port\x18\x06 \x01(\x05R\awssPort\x12*\n" +
	"\bcapacity\x18\a \x01(\v2\x0e.maps.CapacityR\bcapacity\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\b \x01(\tR\tgatewayIp\x12!\n" +
	"\x05error\x18\t \x01(\v2\v.maps.ErrorR\x05error\x12\x1a\n" +
	"\bIdentity\x18\n" +
	" \x01(\tR\bIdentity\"*\n" +
	"\x10GatewayHandshake\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"h\n" +
	"\x10MultipleGateways\x121\n" +
	"\bgateways\x18\x01 \x03(\v2\x15.maps.GatewayResponseR\bgateways\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.maps.ErrorR\x05error\"d\n" +
	"\fProxyMapping\x12!\n" +
	"\fagent_domain\x18\x01 \x01(\tR\vagentDomain\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x19\n" +
	"\bproxy_id\x18\x03 \x01(\tR\aproxyId\"b\n" +
	"\x16ProxyConnectionRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x120\n" +
	"\x14verifiable_cred_hash\x18\x03 \x01(\tR\x12verifiableCredHash\"\xc1\x01\n" +
	"\x19SeederRegistrationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dns\x18\x02 \x01(\tR\x03dns\x12\x17\n" +
	"\aseed_ip\x18\x03 \x01(\tR\x06seedIp\x12\x1b\n" +
	"\tseed_port\x18\x04 \x01(\tR\bseedPort\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x120\n" +
	"\x14verifiable_cred_hash\x18\x06 \x01(\tR\x12verifiableCredHash\"\xe0\x01\n" +
	"\x0eSeederResponse\x12\x1b\n" +
	"\tseeder_id\x18\x01 \x01(\tR\bseederId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03dns\x18\x03 \x01(\tR\x03dns\x12\x17\n" +
	"\aseed_ip\x18\x04 \x01(\tR\x06seedIp\x12\x1b\n" +
	"\tseed_port\x18\x05 \x01(\tR\bseedPort\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1a\n" +
	"\bidentity\x18\a \x01(\tR\bidentity\x12!\n" +
	"\x05error\x18\b \x01(\v2\v.maps.ErrorR\x05error\",\n" +
	"\x12SeederQueryRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"d\n" +
	"\x0fMultipleSeeders\x12.\n" +
	"\aseeders\x18\x01 \x03(\v2\x14.maps.SeederResponseR\aseeders\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.maps.ErrorR\x05error*\xd3\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x03\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x062\xa2\x03\n" +
	"\x04Maps\x12A\n" +
	"\x0fRegisterGateway\x12\x17.maps.GatewayPutRequest\x1a\x15.maps.GatewayResponse\x12B\n" +
	"\rRegisterAgent\x12\x1c.maps.AgentConnectionRequest\x1a\x13.maps.AgentResponse\x12H\n" +
	"\x16ResolveGatewayForAgent\x12\x16.maps.GatewayHandshake\x1a\x16.maps.MultipleGateways\x12A\n" +
	"\x16ResolveGatewayForProxy\x12\x12.maps.ProxyMapping\x1a\x13.maps.AgentResponse\x12G\n" +
	"\x0eRegisterSeeder\x12\x1f.maps.SeederRegistrationRequest\x1a\x14.maps.SeederResponse\x12=\n" +
	"\n" +
	"GetSeeders\x12\x18.maps.SeederQueryRequest\x1a\x15.maps.MultipleSeedersB)Z'github.com/odio4u/agni-schema/maps;mapsb\x06proto3"

var (
	file_maps_maps_proto_rawDescOnce sync.Once
	file_maps_maps_proto_rawDescData []byte
)

func file_maps_maps_proto_rawDescGZIP() []byte {
	file_maps_maps_proto_rawDescOnce.Do(func() {
		file_maps_maps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maps_maps_proto_rawDesc), len(file_maps_maps_proto_rawDesc)))
	})
	return file_maps_maps_proto_rawDescData
}

var file_maps_maps_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_maps_maps_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_maps_maps_proto_goTypes = []any{
	(ErrorCode)(0),                    // 0: maps.ErrorCode
	(*Error)(nil),                     // 1: maps.Error
	(*GatewayPutRequest)(nil),         // 2: maps.GatewayPutRequest
	(*Capacity)(nil),                  // 3: maps.Capacity
	(*GatewayResponse)(nil),           // 4: maps.GatewayResponse
	(*AgentConnectionRequest)(nil),    // 5: maps.AgentConnectionRequest
	(*AgentResponse)(nil),             // 6: maps.AgentResponse
	(*GatewayHandshake)(nil),          // 7: maps.GatewayHandshake
	(*MultipleGateways)(nil),          // 8: maps.MultipleGateways
	(*ProxyMapping)(nil),              // 9: maps.ProxyMapping
	(*ProxyConnectionRequest)(nil),    // 10: maps.ProxyConnectionRequest
	(*SeederRegistrationRequest)(nil), // 11: maps.SeederRegistrationRequest
	(*SeederResponse)(nil),            // 12: maps.SeederResponse
	(*SeederQueryRequest)(nil),        // 13: maps.SeederQueryRequest
	(*MultipleSeeders)(nil),           // 14: maps.MultipleSeeders
}
var file_maps_maps_proto_depIdxs = []int32{
	0,  // 0: maps.Error.code:type_name -> maps.ErrorCode
	3,  // 1: maps.GatewayPutRequest.capacity:type_name -> maps.Capacity
	3,  // 2: maps.GatewayResponse.capacity:type_name -> maps.Capacity
	1,  // 3: maps.GatewayResponse.error:type_name -> maps.Error
	3,  // 4: maps.AgentResponse.capacity:type_name -> maps.Capacity
	1,  // 5: maps.AgentResponse.error:type_name -> maps.Error
	4,  // 6: maps.MultipleGateways.gateways:type_name -> maps.GatewayResponse
	1,  // 7: maps.MultipleGateways.error:type_name -> maps.Error
	1,  // 8: maps.SeederResponse.error:type_name -> maps.Error
	12, // 9: maps.MultipleSeeders.seeders:type_name -> maps.SeederResponse
	1,  // 10: maps.MultipleSeeders.error:type_name -> maps.Error
	2,  // 11: maps.Maps.RegisterGateway:input_type -> maps.GatewayPutRequest
	5,  // 12: maps.Maps.RegisterAgent:input_type -> maps.AgentConnectionRequest
	7,  // 13: maps.Maps.ResolveGatewayForAgent:input_type -> maps.GatewayHandshake
	9,  // 14: maps.Maps.ResolveGatewayForProxy:input_type -> maps.ProxyMapping
	11, // 15: maps.Maps.RegisterSeeder:input_type -> maps.SeederRegistrationRequest
	13, // 16: maps.Maps.GetSeeders:input_type -> maps.SeederQueryRequest
	4,  // 17: maps.Maps.RegisterGateway:output_type -> maps.GatewayResponse
	6,  // 18: maps.Maps.RegisterAgent:output_type -> maps.AgentResponse
	8,  // 19: maps.Maps.ResolveGatewayForAgent:output_type -> maps.MultipleGateways
	6,  // 20: maps.Maps.ResolveGatewayForProxy:output_type -> maps.AgentResponse
	12, // 21: maps.Maps.RegisterSeeder:output_type -> maps.SeederResponse
	14, // 22: maps.Maps.GetSeeders:output_type -> maps.MultipleSeeders
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_maps_maps_proto_init() }
func file_maps_maps_proto_init() {
	if File_maps_maps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maps_maps_proto_rawDesc), len(file_maps_maps_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maps_maps_proto_goTypes,
		DependencyIndexes: file_maps_maps_proto_depIdxs,
		EnumInfos:         file_maps_maps_proto_enumTypes,
		MessageInfos:      file_maps_maps_proto_msgTypes,
	}.Build()
	File_maps_maps_proto = out.File
	file_maps_maps_proto_goTypes = nil
	file_maps_maps_proto_depIdxs = nil
}
